language: python
cache: pip

branches:
  only:
    - master
    - develop

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install .

script:
  - cd tests
  - coverage erase
  - coverage run -a test_simple.py

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kraus@itt.uni-stuttgart.de
    on_success: never
    on_failure: always
