language: python
cache: pip

branches:
  only:
    - master
    - develop

install:
  - pip install -r requirements.txt

script:
  - cd tests
  - pip install .
  - python test_simple.py

# after_success:
#  - coveralls

notifications:
  email:
    recipients:
      - kraus@itt.uni-stuttgart.de
    on_success: change
